feature 1 front end | AZ
Andrew-Z-Z/Wicked-sale-js pull request #2
Opened 2020-01-13 23:15 UTC by Andrew-Z-Z

added three components
rendered products on screen successfully
requires bootstrap polish

2020-01-13 23:16 UTC, Andrew-Z-Z commented
<img width="873" alt="Screen Shot 2020-01-13 at 3 15 43 PM" src="https://user-images.githubusercontent.com/55771037/72300055-929afd00-3617-11ea-8663-55b17bbb9e7b.png">

2020-01-13 23:19 UTC, thebearingedge requested changes
Please use Bootstrap cards per the instructions.

2020-01-14 00:08 UTC, Andrew-Z-Z commented
![Screen Shot 2020-01-13 at 4 06 38 PM](https://user-images.githubusercontent.com/55771037/72302443-e230f700-361e-11ea-9231-ef6ee510beae.png)

2020-01-14 00:14 UTC, thebearingedge approved these changes

2020-01-14 00:29 UTC, merged